# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Figor
version:      1.1
version_from: Figor.pm
installdirs:  site
requires:
    Date::Calc:                    0
    Finance::Account::Archive:     0
    GD::Graph::lines:              0
    Mail::Sendmail:                0.75
    MIME::Base64:                  0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
